---
  name: test
  on:
    push:
      branches:
        - "main"
    pull_request:
      branches:
        - "*"
  jobs:
    lint:
      name: RuboCop
      timeout-minutes: 30
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4
        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: ruby
            bundler-cache: true
        - name: Run RuboCop
          run: bundle exec rubocop
    test:
      name: Ruby ${{ matrix.ruby }}
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          ruby:
            - "2.5"
            - "2.6"
            - "2.7"
            - "3.0"
            - "3.1"
            - "3.2"
            - "3.3"
      steps:
        - uses: actions/checkout@v4

        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: ${{ matrix.ruby }}
            bundler-cache: true

        - name: Run tests
          run: bundle exec rspec
